MODEL:
  BACKBONE: "vgg"
  MAX_SEQ_LEN: 101
  ENCODER_INPUT_SIZE: 512
  ENCODER_HIDDEN_SIZE: 32
  ENCODER_LAYERS: 2
  ENCODER_TYPE: "gru"
  ENCODER_BIDIRECTIONAL: True
INPUT:
  SIZE_CRNN: (32, 400)
  PIXEL_MEAN: 0.9252072
  PIXEL_STD: 0.20963529
  RANDOM_X_TRANSLATION: 0.01
  RANDOM_Y_TRANSLATION: 0.01
  RANDOM_X_SCALING: 0.15
  RANDOM_Y_SCALING: 0.15
  RANDOM_SHEARING: 0.15
  RANDOM_GAMMA: 0.3

DATALOADER:
  NUM_WORKERS: 0
DATASETS:
  TRAIN_PATH: "./data/images/train"
  VAL_PATH: "./data/images/val"
  TEST_PATH: "./data/images/test"
  CHAR_DICT: "./config/dict_number.txt"
SOLVER:
  EPOCHS: 20
  LEARNING_RATE: 0.0001
  LR_SCALE: 0.1
  LR_PERIOD: 205
  BATCH_SIZE: 64
  CHECKPOINT_DIR: "./data/models/"
  CHECKPOINT_NAME: "print_digital.pt"
  PRINT_FREQ: 100
  BATH_SAVING_FREQ: 100
  SAVE_MODEL_FREQ: 2
  WARMUP_EPOCHS: 1
  ENCODER_INIT: "orthogonal"
  DECODER_INIT: "xavier"
  CLIP_GRAD: 10
  OPTIMIZER: "adam"
  PRETRAINED_MODEL: ""
TEST:
  BATCH_SIZE: 1
  CRNN_MODEL: "./data/models/print_digital.pt"
LOG:
  PATH: "logs"
  NAME: "log.txt"
  LEVEL_NAME: "INFO"
MISC:
  USE_LINE_CATEGORY: True
  ILLUMINATION_COMPENSATION: False
  BINARYZATION: False
  BIFILTER: False
  EXTRA_DATASET: False
